layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:  
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  linkedin: Guarinho
  medium: Guarinho
  website: http://guarinho.ml
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
    
  # mastodon: your_username
  
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
    
  # youtube: your_username

topics:
  - name: Machine Learning
    web_url: https://github.com/topics/machine-learning
    image_url: "https://tecnoblog.net/wp-content/uploads/2018/06/digital-brain.jpg"
    
  - name: 3D Models
    web_url: https://github.com/topics/3d
    image_url: "https://i.pinimg.com/originals/0f/d4/19/0fd4195dc11445a476a93d27c9a2091e.jpg"  
    
  - name: Python 
    web_url: https://github.com/topics/python
    image_url: "https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/python/python.png"


